timezone: Europe/Oslo
encoding: utf-8
exclude: ["vendor"]
name: Matforslag
baseurl: /matforslag

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      title: "Matforslag"

sass:
  sass_dir: _sass
  style: compressed
